export const NAAT_PRESETS = [
  {
    name: "Primer/probe screening",
    numOfSampleConcentrations: 3,
    numOfTechnicalReplicates: 3,
    mastermixVolumePerReaction: 18,
    sampleVolumePerReaction: 2,
    pcrPlateSize: 96,
    mastermixes: [
      {
        nameOfMastermix: "Mix A - 0.2 uM",
        orderIndex: 1,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix A",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "Mix A - 0.3 uM",
        orderIndex: 2,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix A",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "Mix A - 0.1 uM",
        orderIndex: 3,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix A",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "Mix B - 0.2 uM",
        orderIndex: 4,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix B",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "Mix B - 0.3 uM",
        orderIndex: 5,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix B",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "Mix B - 0.1 uM",
        orderIndex: 6,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix B",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
    ],
  },
  {
    name: "Mastermix formulation",
    numOfSampleConcentrations: 3,
    numOfTechnicalReplicates: 3,
    mastermixVolumePerReaction: 23,
    sampleVolumePerReaction: 2,
    pcrPlateSize: 96,
    mastermixes: [
      {
        nameOfMastermix: "1",
        orderIndex: 1,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.25,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "2",
        orderIndex: 2,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.1,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "3",
        orderIndex: 3,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.25,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "4",
        orderIndex: 4,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.1,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "5",
        orderIndex: 5,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.1,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "6",
        orderIndex: 6,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.25,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "7",
        orderIndex: 7,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.175,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "8",
        orderIndex: 8,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.1,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.175,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "9",
        orderIndex: 9,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.1,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "10",
        orderIndex: 10,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.1,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.25,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "11",
        orderIndex: 11,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.1,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.1,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.25,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "12",
        orderIndex: 12,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.1,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "13",
        orderIndex: 13,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 7.5,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.175,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "14",
        orderIndex: 14,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.175,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
    ],
  },
  {
    name: "Limit of detection analysis",
    numOfSampleConcentrations: 8,
    numOfTechnicalReplicates: 6,
    mastermixVolumePerReaction: 23,
    sampleVolumePerReaction: 2,
    pcrPlateSize: 96,
    mastermixes: [
      {
        nameOfMastermix: "1",
        orderIndex: 1,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.3,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.3,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 4,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.1,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
      {
        nameOfMastermix: "2",
        orderIndex: 2,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 2.5,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.175,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
    ],
  },
  {
    name: "Probit",
    numOfSampleConcentrations: 5,
    numOfTechnicalReplicates: 20,
    mastermixVolumePerReaction: 23,
    sampleVolumePerReaction: 2,
    pcrPlateSize: 96,
    mastermixes: [
      {
        nameOfMastermix: "1",
        orderIndex: 1,
        recipes: [
          {
            orderIndex: 1,
            finalSource: "Water",
            unit: "X",
            finalConcentration: 0,
            stockConcentration: 0,
            liquidType: "water",
            dispenseType: "Jet_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 2,
            finalSource: "PCR buffer",
            unit: "X",
            finalConcentration: 1,
            stockConcentration: 10,
            liquidType: "buffer",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 3,
            finalSource: "Primer/probe mix",
            unit: "uM",
            finalConcentration: 0.2,
            stockConcentration: 10,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 4,
            finalSource: "dNTP mix",
            unit: "mM",
            finalConcentration: 0.2,
            stockConcentration: 25,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 5,
            finalSource: "MgCl2",
            unit: "mM",
            finalConcentration: 1,
            stockConcentration: 50,
            liquidType: "primers",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
          {
            orderIndex: 6,
            finalSource: "Taq pol",
            unit: "U/uL",
            finalConcentration: 0.125,
            stockConcentration: 5,
            liquidType: "enzymes",
            dispenseType: "Surface_Empty",
            tipWashing: "No",
          },
        ],
      },
    ],
  },
];
